### ISSUE TITLE
Typo in modernpro-coverletter.typ for cl-title

### ISSUE THREAD

**Issue by SiIverHusky** [jxpeng98/typst-coverletter#2]
In line 70, it does `postcode != []` instead of `cl-title != []`. This would mean that the title would not be shown without the post code.

I assume this is a mistake and not the intended functionality.

**Comment by jxpeng98** [comment]
Hello @SiIverHusky ,
Many thanks for the issue. You are right. I did not notice this error since I always included the postcode in my cover letter writing. 


I have fixed it. The new version will be available in Typst Universe very soon.

Thanks again!

**Comment by SiIverHusky** [comment]
Thanks for the fix 🙏🏽
